services:
  dashboard:
    container_name: dashboard-web-1
    build: .
    expose:
      - "8004"
    env_file:
      - .env
    volumes:
      - dashboard_static:/app/staticfiles
      - ./favorites.json:/app/favorites.json
      - ./notes.txt:/app/notes.txt
    restart: always
    networks:
      - shared
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  dashboard_static:
    external: true

networks:
  shared:
    external: true
    name: shared_network